# This is based on docker-compose.dev.yml, with the difference that
# the volumes are mounted using 'delegated', which is significantly
# faster on a mac (cutting startup time for the java app approximately
# in half)
# See https://docs.docker.com/docker-for-mac/osxfs-caching/
version: '3'
services:
  mongodb:
    image: mongo:5.0.14
    volumes:
     - ./mongo/data:/data/db
  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile-static
    ports:
     - "8443:8443"
    volumes:
     - ./src/main/resources/:/usr/local/apache2/htdocs/:delegated
    depends_on:
     - server
  server:
    build:
      context: ./server-dev
    ports:
     - "9999:9999"
    volumes:
     - ./target/:/server/:delegated
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
