apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  creationTimestamp: null
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    app.gitlab.com/app: "{{ .Values.application.path_slug }}"
    app.gitlab.com/env: "{{ .Values.application.env_slug }}"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
      annotations:
        app.gitlab.com/app: "{{ .Values.application.path_slug }}"
        app.gitlab.com/env: "{{ .Values.application.env_slug }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: BASE_URL
          value: {{ .Values.service.url | quote }}
        - name: BASE_MTLS_URL
          value: {{ .Values.service.mtls | quote }}
        - name: MONGODB_HOST
          value: {{ template "appname" . }}-mongodb
        - name: JAVA_EXTRA_ARGS
          value: {{ .Values.javaArgs | quote }}
        - name: JWKS
          valueFrom:
            secretKeyRef:
              name: jwks-{{ template "appname" . }}
              key: jwks
              optional: true
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwks-{{ template "appname" . }}
              key: signingKey
              optional: true
        - name: OIDC_GOOGLE_CLIENTID
          valueFrom:
            secretKeyRef:
              name: oidc-google-credentials
              key: clientid
        - name: OIDC_GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-google-credentials
              key: secret
        - name: OIDC_GITLAB_CLIENTID
          valueFrom:
            secretKeyRef:
              name: oidc-gitlab-credentials
              key: clientid
        - name: OIDC_GITLAB_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-gitlab-credentials
              key: secret
        volumeMounts:
            - name: dump-volume
              mountPath:
                /dump
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          successThreshold: 1
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          failureThreshold: 3
          successThreshold: 1
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
          - name: dump-volume
            persistentVolumeClaim:
                claimName: {{ template "trackableappnamepvc" . }}
status: {}
